// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UMS.Models;

namespace UMS.Migrations
{
    [DbContext(typeof(EditProfileContext))]
    partial class EditProfileContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("UMS.Models.EditProfile", b =>
                {
                    b.Property<string>("acc_Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("acc_Firstname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("acc_Lastname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("acc_PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("acc_Id");

                    b.ToTable("EditProfile");
                });
#pragma warning restore 612, 618
        }
    }
}
